mfd: mx77663: Fix build failure for undefined reference
Fixing build failure what undefined reference to max77663_xxx APIs when
didn't built-in max77663 mfd core driver.

Signed-off-by: Jin Park <jinyoungp@nvidia.com>
Reviewed-on: http://git-master/r/58579
(cherry picked from commit 99baa03a6d3401228f58c13a7dad5228f59d8718)

Change-Id: I971e132ec9ca12a4ce4bc47897c3722d07b93cbd
Reviewed-on: http://git-master/r/59890
Reviewed-by: Varun Colbert <vcolbert@nvidia.com>
Tested-by: Varun Colbert <vcolbert@nvidia.com>

Rebase-Id: R0d9ce223d77c4005fa3c4c75dd5ac3221417a578